nome = str(input("Qual é o nome do produto? "))
preço = float(input("Qual é o preço do produto? "))
categoria_ou_tipo = str(input("Qual a categoria ou o tipo do produto? "))
quantidade = int(input("Qual é a quantidade disponível em estoque? "))
validade = str(input("Qual é a data de validade? Caso aplicável "))